Mobile portfolio project pull request
Ferizad/Mobile-portfolio pull request #1
Opened 2022-12-02 09:34 UTC by Ferizad

2022-12-02 10:09 UTC, Debas-31 reviewed
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle:  :red_circle:  :red_circle: 

- [ ] You have submitted a project with Pull Request and should not have a summary describing introduced changes in more detail.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-02 13:17 UTC, frank1738 approved these changes
Hi @Ferizad , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/f9RzoxHizH72k15FKS/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Good Design👍

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 13:17 UTC, frank1738 commented on README.md
> +>>>>>>> af642373f43c6a0e09147fdb7af75fd4084f44fb
- [ OPTIONAL] Kindly remove unnecessary comments from your readme file to keep it clean and professional

2022-12-02 13:17 UTC, frank1738 commented on README.md
> +>>>>>>> af642373f43c6a0e09147fdb7af75fd4084f44fb
- [ OPTIONAL] Kindly remove unnecessary comments from your readme file to keep it clean and professional

2022-12-02 16:59 UTC, Ferizad commented
"Works" and "mobile section" were added in HTML and CSS files.

2022-12-02 17:51 UTC, mugishasam123 requested changes
Hi @Ferizad  👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![alt](https://media.tenor.com/Pxh2kc7GmDoAAAAM/dog-so-close.gif)
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors 👍 
- Descriptive PR title 🥇 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 17:51 UTC, mugishasam123 commented on index.html
> +
- [ ] Please try to stick to the Figma design as much as possible to make your project looks good. you can do so by leveraging colors, fonts, and font sizes.

Your design:
![image](https://user-images.githubusercontent.com/90524466/205352676-2d168dde-cbc4-4f25-905f-f0248d195166.png)

Figma design:
![image](https://user-images.githubusercontent.com/90524466/205352859-42084194-189c-4307-81eb-e056b4c547a9.png)

2022-12-02 17:51 UTC, mugishasam123 commented on index.html
> +                <li>
- [ ] Please you should stick to the design as much as possible to make your work more professional, try to match your design with the given one.

Your design:
![image](https://user-images.githubusercontent.com/90524466/205353718-19cd05e5-2b24-487a-8ae1-403ff95de590.png)

Figma design:
![image](https://user-images.githubusercontent.com/90524466/205353791-a3d08f92-9c23-44d6-bcb0-9bd08e147518.png)

2022-12-03 05:37 UTC, Ferizad commented
Modified HMTL and CSS files to stick to Figma design. Added vector icons in the last frameworks, and skills part.

2022-12-03 06:01 UTC, amejid requested changes
Hi @Ferizad , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Highlights
- Good UI design :heavy_check_mark: 
- Good commit history :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 08:57 UTC, Ferizad commented
Updated HTML and CSS files to change the font size on the last part according to the Figma template.

2022-12-03 09:08 UTC, algerina approved these changes
Hi @Ferizad , 
Good job so far! 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 
<img src="https://media0.giphy.com/media/l7fdqmHQ1jCg2HzQlx/giphy.gif"/>

 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2022-12-04 11:54 UTC, merged