Pair programming 1 for mobile portfolio
Ferizad/Mobile-portfolio pull request #3
Opened 2022-12-08 10:16 UTC by Ferizad

Added form, name, email, and a text part.

2022-12-08 12:49 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :

Hi @Ferizad , 

Good job... you have done generally well emplenting the requirements for this milestone.
just a few issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights :tophat:  :+1: 
- [ ] No linter errors :clap: :clap: :clap: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ OPTIONAL] __I suggest to edit your README file and remove the unprofessional fields as it will give a better image of your great work__ :sunglasses: 
- [OPTIONAL ] __Kindly make sure you submit the same PR for all the reviews you submit since it allows to keep track of the evolution of your work___ :pray: 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 12:49 UTC, GedeonTS commented on index.html
> +              <label>
- [ ] Good job adding action and method attributes for the form, I think it's not necessary to have `<field>` and labels kindely remove them :recycle:

2022-12-08 12:49 UTC, GedeonTS commented on index.html
> +              </label>
- [ ] :recycle: Kindly make sure your design stick to the figma design, by giving to your submit button width and colors:

- Your design:
![YourButton](https://user-images.githubusercontent.com/97834160/206446952-d4e25ab0-d120-4bbe-afab-cc6b37e05b74.png)


- Figma design:
![figButton](https://user-images.githubusercontent.com/97834160/206447907-84ee5501-40d6-40da-bd17-36484c503b8c.png)

2022-12-08 15:44 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Ferizad , |
|Great work on making the changes requested by a previous reviewer 👏, You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. |
| <img src="https://media0.giphy.com/media/qQdL532ZANbjy/giphy.gif"/> |

## Highlights

- [ ]...✅ Good commit messages 
- [ ]...✅ Green linters 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-08 15:44 UTC, joskalenda commented on index.html
> +              </label>
- [ ] As mentioned by the previous reviewer, your background and your button style and color are not matching the original design, please make sure you fix it and resubmit your work, after that, you will be good to go, but the meanwhile, please take a look at this image below to compare, this is the color code `#6070ff` you are using in your CSS for your `button background`. 
<img width="760" alt="rep" src="https://user-images.githubusercontent.com/77843050/206485372-afb18540-5618-449c-85a2-1d2aedc6e7d2.png">

- [ ] -[OPTIONAL] Those 2 arrows pointing to the input files are showing the black border you have added to your design, We understand you may want to make it more nice and awesome but please remember that it is said to stick on the Figma design, pay attention to details please, this comment is marked as optional because it was not mentioned in the previous review but I would suggest you on it as we move onto the next project parts.

2022-12-09 05:54 UTC, emmiiorji requested changes
Hi @Ferizad, 

# Status: Changes Required ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![A little bit more](https://user-images.githubusercontent.com/20554583/206632836-36f974fe-77bd-4da3-9fb0-472bbb79c713.gif)

 ## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Adhered to GitHub flow


 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 05:54 UTC, emmiiorji commented on style.css
> +  background: linear-gradient(rgba(96, 112, 255, 0.85), rgba(96, 112, 255, 0.85)), url(media/background2.jpg);
You seem to have missed out on this suggestion by the previous reviewers, kindly use the color as it appears on the figma design. The color used on figma is `#6070FF`

Please, fix this and your project will be ready for approval.

Your design:
![image](https://user-images.githubusercontent.com/20554583/206633552-df4725b4-91de-47a4-961a-42aea5194379.png)

Figma design:
![image](https://user-images.githubusercontent.com/20554583/206633589-7768609f-f65e-4bef-955f-778703f618a5.png)

2022-12-09 07:53 UTC, roshan-bajgain approved these changes
Hi @Ferizad, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-09 07:55 UTC, merged